#!/usr/bin/env python3
"""Detect vehicles in a UAV frame and project detections onto the reference map."""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import cv2
import numpy as np

try:
    from georeference_map import (
        DEFAULT_GEOREF_JSON,
        DEFAULT_MAP_IMAGE,
        draw_label,
        find_best_match,
        load_georef,
        map_query_point,
        read_bgr,
        resolve_map_image_path,
        resize_to_fit,
        show_image,
        write_image,
    )
except ModuleNotFoundError:
    from scripts.georeference_map import (
        DEFAULT_GEOREF_JSON,
        DEFAULT_MAP_IMAGE,
        draw_label,
        find_best_match,
        load_georef,
        map_query_point,
        read_bgr,
        resolve_map_image_path,
        resize_to_fit,
        show_image,
        write_image,
    )


DEFAULT_FRAME = Path("extracted_frames/frame_000051.jpg")
DEFAULT_OUTPUT_ROOT = Path("vehicle_localization_outputs")
DEFAULT_YOLO_MODEL = "yolo26x.pt"
DEFAULT_VEHICLE_CLASSES = "car"


@dataclass
class Detection:
    bbox_xyxy: tuple[float, float, float, float]
    confidence: float
    class_name: str
    detector: str
    target_verification: dict[str, Any] | None = None

    @property
    def center(self) -> tuple[float, float]:
        x1, y1, x2, y2 = self.bbox_xyxy
        return (x1 + x2) / 2.0, (y1 + y2) / 2.0

    @property
    def area(self) -> float:
        x1, y1, x2, y2 = self.bbox_xyxy
        return max(0.0, x2 - x1) * max(0.0, y2 - y1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Detect vehicles in a UAV frame, localize their centers on "
            "the default compressed UAV georeferenced basemap, and save demo visualizations."
        )
    )
    parser.add_argument("--frame", type=Path, default=DEFAULT_FRAME)
    parser.add_argument("--map-image", type=Path, default=DEFAULT_MAP_IMAGE)
    parser.add_argument(
        "--georef-json",
        type=Path,
        default=DEFAULT_GEOREF_JSON,
        help=(
            "Optional georeferenced basemap JSON generated by "
            f"scripts/create_georeferenced_basemap.py. Default: {DEFAULT_GEOREF_JSON}"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Output directory. Default: vehicle_localization_outputs/<frame filename stem>."
        ),
    )

    parser.add_argument(
        "--detector",
        choices=("auto", "yolo", "white-heuristic"),
        default="auto",
        help="auto tries YOLO first and falls back to a white-vehicle heuristic.",
    )
    parser.add_argument("--yolo-model", default=DEFAULT_YOLO_MODEL)
    parser.add_argument("--vehicle-classes", default=DEFAULT_VEHICLE_CLASSES)
    parser.add_argument(
        "--device",
        default=None,
        help=(
            "YOLO inference device passed to Ultralytics, e.g. cpu, mps, cuda, "
            "cuda:0. Default lets Ultralytics choose."
        ),
    )
    parser.add_argument(
        "--yolo-batch-size",
        type=int,
        default=1,
        help=(
            "Number of tile/upscale images to send to each YOLO predict call. "
            "Use values like 4 or 8 on CUDA/MPS if memory allows. Default: 1"
        ),
    )
    parser.add_argument("--conf", type=float, default=0.12)
    parser.add_argument("--model-iou", type=float, default=0.55)
    parser.add_argument("--nms-iou", type=float, default=0.45)
    parser.add_argument("--imgsz", type=int, default=1280)
    parser.add_argument("--tile-size", type=int, default=960)
    parser.add_argument("--tile-overlap", type=int, default=240)
    parser.add_argument(
        "--tile-upscales",
        default="1,2",
        help="Comma-separated tile upscales. Use larger values when cars are tiny.",
    )
    parser.add_argument("--max-detections", type=int, default=40)

    parser.add_argument("--heuristic-min-area", type=float, default=450.0)
    parser.add_argument("--heuristic-max-area", type=float, default=16000.0)
    parser.add_argument(
        "--target-verifier",
        action=argparse.BooleanOptionalAction,
        default=False,
        help=(
            "Keep only detections that look like a white vehicle with a visible red/pink "
            "target marker on the vehicle. Default: disabled."
        ),
    )
    parser.add_argument(
        "--target-verifier-min-score",
        type=float,
        default=0.18,
        help="Minimum marker verification score when --target-verifier is enabled. Default: 0.18",
    )
    parser.add_argument(
        "--target-verifier-context",
        type=float,
        default=0.15,
        help=(
            "Small extra context around each vehicle box, as a fraction of the larger box side, "
            "used by the target verifier. Keep this small so off-vehicle red objects are less "
            "likely to pass. Default: 0.15"
        ),
    )
    parser.add_argument(
        "--target-verifier-min-white-ratio",
        type=float,
        default=0.15,
        help="Minimum white-pixel ratio inside the original vehicle box. Default: 0.15",
    )
    parser.add_argument(
        "--target-verifier-min-red-pixels",
        type=int,
        default=35,
        help="Minimum red/pink marker pixels required by the target verifier. Default: 35",
    )
    parser.add_argument(
        "--target-verifier-proposals",
        action=argparse.BooleanOptionalAction,
        default=False,
        help=(
            "When --target-verifier is enabled, add lightweight white-vehicle candidates "
            "around visible red/pink markers before filtering. Default: disabled"
        ),
    )

    parser.add_argument(
        "--map-method",
        choices=("auto", "feature", "template"),
        default="auto",
        help=(
            "Reference-map matching method. Auto tries downscaled SIFT/ORB + RANSAC "
            "first, then falls back to template matching."
        ),
    )
    parser.add_argument(
        "--orientations",
        choices=("none", "rotations", "flips", "all"),
        default="rotations",
    )
    parser.add_argument("--template-scales", default="0.12,0.10,0.08,0.07,0.06,0.05,0.04")
    parser.add_argument("--min-template-score", type=float, default=0.45)
    parser.add_argument(
        "--orientation-switch-margin",
        type=float,
        default=0.08,
        help=(
            "When testing rotations, keep identity unless the best rotated match exceeds "
            "identity by this score margin. Default: 0.08"
        ),
    )
    parser.add_argument("--max-features", type=int, default=8000)
    parser.add_argument(
        "--feature-max-dim",
        type=int,
        default=1800,
        help=(
            "Downscale map/query images so their longest side is at most this "
            "many pixels before feature matching. Use 0 to disable. Default: 1800"
        ),
    )
    parser.add_argument("--ratio", type=float, default=0.75)
    parser.add_argument("--min-matches", type=int, default=20)
    parser.add_argument("--min-inliers", type=int, default=10)
    parser.add_argument(
        "--match-workers",
        type=int,
        default=1,
        help=(
            "Parallel workers for independent map-orientation matching. "
            "Use 1 to keep the original sequential behavior. Default: 1"
        ),
    )

    parser.add_argument("--save-crops", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument(
        "--show",
        action="store_true",
        help="Open an OpenCV window showing the process overview image after saving outputs.",
    )
    return parser.parse_args()


def parse_float_list(raw: str, argument_name: str) -> list[float]:
    values = [float(part.strip()) for part in raw.split(",") if part.strip()]
    if not values:
        raise ValueError(f"{argument_name} must contain at least one value")
    if any(value <= 0 for value in values):
        raise ValueError(f"{argument_name} values must be positive")
    return values


def parse_class_filter(raw: str) -> set[str] | None:
    if raw.strip().lower() in {"", "all", "*"}:
        return None
    return {item.strip().lower() for item in raw.split(",") if item.strip()}


def generate_tiles(width: int, height: int, tile_size: int, overlap: int) -> list[tuple[int, int, int, int]]:
    if tile_size <= 0:
        raise ValueError("--tile-size must be positive")
    if overlap < 0 or overlap >= tile_size:
        raise ValueError("--tile-overlap must be non-negative and smaller than --tile-size")

    step = tile_size - overlap
    x_starts = list(range(0, max(width - tile_size, 0) + 1, step))
    y_starts = list(range(0, max(height - tile_size, 0) + 1, step))
    if not x_starts or x_starts[-1] != max(width - tile_size, 0):
        x_starts.append(max(width - tile_size, 0))
    if not y_starts or y_starts[-1] != max(height - tile_size, 0):
        y_starts.append(max(height - tile_size, 0))

    tiles = []
    for y in y_starts:
        for x in x_starts:
            tiles.append((x, y, min(tile_size, width - x), min(tile_size, height - y)))
    return tiles


def detect_with_yolo(
    image: np.ndarray,
    args: argparse.Namespace,
    upscales: list[float],
    class_filter: set[str] | None,
) -> list[Detection]:
    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise RuntimeError(
            "ultralytics is not installed. Install requirements or use "
            "--detector white-heuristic for an offline demo."
        ) from exc

    model = YOLO(args.yolo_model)
    names = getattr(model, "names", {})
    tiles = generate_tiles(image.shape[1], image.shape[0], args.tile_size, args.tile_overlap)
    detections: list[Detection] = []
    batch_size = max(1, int(args.yolo_batch_size))
    batch_inputs: list[np.ndarray] = []
    batch_meta: list[tuple[int, int, float]] = []

    def flush_batch() -> None:
        if not batch_inputs:
            return
        predict_kwargs: dict[str, Any] = {
            "source": batch_inputs if len(batch_inputs) > 1 else batch_inputs[0],
            "imgsz": args.imgsz,
            "conf": args.conf,
            "iou": args.model_iou,
            "batch": batch_size,
            "verbose": False,
        }
        if args.device:
            predict_kwargs["device"] = args.device
        results = model.predict(**predict_kwargs)
        for result, (tile_x, tile_y, upscale) in zip(results, batch_meta):
            boxes = result.boxes
            if boxes is None:
                continue
            xyxy = boxes.xyxy.cpu().numpy()
            confs = boxes.conf.cpu().numpy()
            classes = boxes.cls.cpu().numpy().astype(int)
            for bbox, confidence, class_id in zip(xyxy, confs, classes):
                class_name = str(names.get(int(class_id), class_id)).lower()
                if class_filter is not None and class_name not in class_filter:
                    continue
                x1, y1, x2, y2 = [float(value) / upscale for value in bbox]
                detections.append(
                    Detection(
                        bbox_xyxy=(
                            clamp(x1 + tile_x, 0, image.shape[1] - 1),
                            clamp(y1 + tile_y, 0, image.shape[0] - 1),
                            clamp(x2 + tile_x, 0, image.shape[1] - 1),
                            clamp(y2 + tile_y, 0, image.shape[0] - 1),
                        ),
                        confidence=float(confidence),
                        class_name=class_name,
                        detector=f"yolo:{args.yolo_model}:tile_x{upscale:g}",
                    )
                )
        batch_inputs.clear()
        batch_meta.clear()

    for tile_x, tile_y, tile_width, tile_height in tiles:
        tile = image[tile_y : tile_y + tile_height, tile_x : tile_x + tile_width]
        for upscale in upscales:
            if math.isclose(upscale, 1.0):
                model_input = tile
            else:
                model_input = cv2.resize(
                    tile,
                    (max(1, round(tile_width * upscale)), max(1, round(tile_height * upscale))),
                    interpolation=cv2.INTER_CUBIC,
                )

            batch_inputs.append(model_input)
            batch_meta.append((tile_x, tile_y, upscale))
            if len(batch_inputs) >= batch_size:
                flush_batch()

    flush_batch()
    return apply_nms(detections, args.nms_iou, args.max_detections)


def detect_white_vehicle_candidates(image: np.ndarray, args: argparse.Namespace) -> list[Detection]:
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, (0, 0, 165), (180, 80, 255))
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=2)

    contours, _hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    detections: list[Detection] = []
    for contour in contours:
        x, y, width, height = cv2.boundingRect(contour)
        bbox_area = float(width * height)
        if bbox_area < args.heuristic_min_area or bbox_area > args.heuristic_max_area:
            continue
        if width < 12 or height < 12:
            continue
        aspect = width / float(height)
        if not 0.30 <= aspect <= 4.50:
            continue
        contour_area = cv2.contourArea(contour)
        extent = contour_area / bbox_area if bbox_area else 0.0
        if extent < 0.28:
            continue
        confidence = min(0.99, 0.30 + extent * 0.45 + min(bbox_area / 8000.0, 1.0) * 0.20)
        detections.append(
            Detection(
                bbox_xyxy=(float(x), float(y), float(x + width), float(y + height)),
                confidence=float(confidence),
                class_name="white_vehicle_candidate",
                detector="white-heuristic",
            )
        )
    return apply_nms(detections, args.nms_iou, args.max_detections)


def detect_target_marker_vehicle_candidates(image: np.ndarray, args: argparse.Namespace) -> list[Detection]:
    red_mask = build_red_marker_mask(image)
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    white_mask = cv2.inRange(hsv, (0, 0, 145), (180, 95, 255))
    white_mask = cv2.morphologyEx(
        white_mask,
        cv2.MORPH_CLOSE,
        cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5)),
        iterations=1,
    )
    contours, _hierarchy = cv2.findContours(red_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    detections: list[Detection] = []
    image_height, image_width = image.shape[:2]
    for contour in contours:
        red_x, red_y, red_width, red_height = cv2.boundingRect(contour)
        red_pixels = int(cv2.countNonZero(red_mask[red_y : red_y + red_height, red_x : red_x + red_width]))
        if red_pixels < args.target_verifier_min_red_pixels or red_width < 6 or red_height < 6:
            continue

        marker_side = max(red_width, red_height)
        pad = max(24, int(marker_side * 3.0))
        sx1 = int(clamp(red_x - pad, 0, image_width - 1))
        sy1 = int(clamp(red_y - pad, 0, image_height - 1))
        sx2 = int(clamp(red_x + red_width + pad, sx1 + 1, image_width))
        sy2 = int(clamp(red_y + red_height + pad, sy1 + 1, image_height))
        search_white = white_mask[sy1:sy2, sx1:sx2]
        white_contours, _white_hierarchy = cv2.findContours(search_white, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        best_bbox: tuple[int, int, int, int] | None = None
        best_score = 0.0
        for white_contour in white_contours:
            wx, wy, ww, wh = cv2.boundingRect(white_contour)
            if ww < 10 or wh < 10:
                continue
            x1, y1 = sx1 + wx, sy1 + wy
            x2, y2 = x1 + ww, y1 + wh
            red_cx = red_x + red_width / 2.0
            red_cy = red_y + red_height / 2.0
            expanded = max(5, int(max(ww, wh) * 0.12))
            if not (x1 - expanded <= red_cx <= x2 + expanded and y1 - expanded <= red_cy <= y2 + expanded):
                continue

            bbox_area = float(ww * wh)
            if bbox_area < max(120.0, args.heuristic_min_area * 0.25):
                continue
            if bbox_area > max(args.heuristic_max_area * 4.0, 90000.0):
                continue
            aspect = ww / float(wh)
            if not 0.20 <= aspect <= 5.50:
                continue
            white_ratio = vehicle_white_ratio(image, (x1, y1, x2, y2))
            if white_ratio < max(0.25, args.target_verifier_min_white_ratio * 0.60):
                continue

            red_density = red_pixels / float(max(1, red_width * red_height))
            score = white_ratio * 0.45 + red_density * 0.35 + min(1.0, red_pixels / 250.0) * 0.20
            if score > best_score:
                union_x1 = int(clamp(min(x1, red_x) - expanded, 0, image_width - 1))
                union_y1 = int(clamp(min(y1, red_y) - expanded, 0, image_height - 1))
                union_x2 = int(clamp(max(x2, red_x + red_width) + expanded, union_x1 + 1, image_width))
                union_y2 = int(clamp(max(y2, red_y + red_height) + expanded, union_y1 + 1, image_height))
                best_bbox = (union_x1, union_y1, union_x2, union_y2)
                best_score = score

        if best_bbox is None:
            continue
        detections.append(
            Detection(
                bbox_xyxy=tuple(float(value) for value in best_bbox),
                confidence=float(min(0.99, 0.35 + best_score * 0.50)),
                class_name="target_marker_vehicle_candidate",
                detector="target-verifier-proposal",
            )
        )

    return apply_nms(detections, args.nms_iou, args.max_detections)


def filter_target_detections(
    image: np.ndarray,
    detections: list[Detection],
    args: argparse.Namespace,
) -> tuple[list[Detection], dict[str, Any]]:
    if not args.target_verifier:
        return detections, {"enabled": False}

    kept: list[Detection] = []
    rejected: list[dict[str, Any]] = []
    for index, detection in enumerate(detections, start=1):
        crop, crop_box = crop_detection_context(image, detection.bbox_xyxy, args.target_verifier_context)
        verification = verify_red_marker(crop, args.target_verifier_min_red_pixels)
        white_ratio = vehicle_white_ratio(image, detection.bbox_xyxy)
        verification.update(
            {
                "enabled": True,
                "threshold": args.target_verifier_min_score,
                "min_white_ratio": args.target_verifier_min_white_ratio,
                "min_red_pixels": args.target_verifier_min_red_pixels,
                "vehicle_white_ratio": white_ratio,
                "context_bbox_xyxy": [round(float(value), 3) for value in crop_box],
            }
        )
        detection.target_verification = verification
        is_verified = (
            verification["score"] >= args.target_verifier_min_score
            and white_ratio >= args.target_verifier_min_white_ratio
        )
        if is_verified:
            kept.append(detection)
        else:
            reason = verification["reason"]
            if verification["score"] >= args.target_verifier_min_score:
                reason = "white_vehicle_ratio_below_threshold"
            rejected.append(
                {
                    "candidate": f"veh_{index:03d}",
                    "class_name": detection.class_name,
                    "confidence": round(detection.confidence, 4),
                    "score": verification["score"],
                    "vehicle_white_ratio": white_ratio,
                    "reason": reason,
                }
            )

    summary = {
        "enabled": True,
        "threshold": args.target_verifier_min_score,
        "min_white_ratio": args.target_verifier_min_white_ratio,
        "min_red_pixels": args.target_verifier_min_red_pixels,
        "input_count": len(detections),
        "kept_count": len(kept),
        "rejected_count": len(rejected),
        "rejected": rejected,
    }
    return kept, summary


def vehicle_white_ratio(
    image: np.ndarray,
    bbox_xyxy: tuple[float, float, float, float],
) -> float:
    x1, y1, x2, y2 = [int(round(value)) for value in bbox_xyxy]
    x1 = int(clamp(x1, 0, image.shape[1] - 1))
    y1 = int(clamp(y1, 0, image.shape[0] - 1))
    x2 = int(clamp(x2, x1 + 1, image.shape[1]))
    y2 = int(clamp(y2, y1 + 1, image.shape[0]))
    crop = image[y1:y2, x1:x2]
    if crop.size == 0:
        return 0.0
    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)
    white_mask = cv2.inRange(hsv, (0, 0, 145), (180, 95, 255))
    return round(float(cv2.countNonZero(white_mask) / max(1, crop.shape[0] * crop.shape[1])), 4)


def crop_detection_context(
    image: np.ndarray,
    bbox_xyxy: tuple[float, float, float, float],
    context_fraction: float,
) -> tuple[np.ndarray, tuple[float, float, float, float]]:
    x1, y1, x2, y2 = bbox_xyxy
    width = max(1.0, x2 - x1)
    height = max(1.0, y2 - y1)
    pad = max(width, height) * max(0.0, context_fraction)
    crop_box = (
        clamp(x1 - pad, 0, image.shape[1] - 1),
        clamp(y1 - pad, 0, image.shape[0] - 1),
        clamp(x2 + pad, 0, image.shape[1] - 1),
        clamp(y2 + pad, 0, image.shape[0] - 1),
    )
    cx1, cy1, cx2, cy2 = [int(round(value)) for value in crop_box]
    return image[cy1 : max(cy1 + 1, cy2), cx1 : max(cx1 + 1, cx2)], crop_box


def build_red_marker_mask(image: np.ndarray) -> np.ndarray:
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    hue_red_mask = cv2.bitwise_or(
        cv2.inRange(hsv, (0, 45, 70), (14, 255, 255)),
        cv2.inRange(hsv, (165, 45, 70), (180, 255, 255)),
    )
    blue_channel, green_channel, red_channel = cv2.split(image)
    pink_mask = (
        (red_channel.astype(np.int16) > green_channel.astype(np.int16) + 10)
        & (red_channel.astype(np.int16) > blue_channel.astype(np.int16) + 3)
        & (red_channel > 125)
    ).astype(np.uint8) * 255
    red_mask = cv2.bitwise_or(hue_red_mask, pink_mask)
    return cv2.morphologyEx(
        red_mask,
        cv2.MORPH_CLOSE,
        cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3)),
        iterations=1,
    )


def verify_red_marker(crop: np.ndarray, min_red_pixels: int = 35) -> dict[str, Any]:
    if crop.size == 0:
        return {"score": 0.0, "reason": "empty_crop"}

    red_mask = build_red_marker_mask(crop)
    contours, _hierarchy = cv2.findContours(red_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    components: list[dict[str, Any]] = []
    for contour in contours:
        x, y, width, height = cv2.boundingRect(contour)
        red_pixels = int(cv2.countNonZero(red_mask[y : y + height, x : x + width]))
        if red_pixels < min_red_pixels or width < 6 or height < 6:
            continue
        aspect = width / float(height)
        if not 0.25 <= aspect <= 4.00:
            continue
        marker_side = max(width, height)
        if marker_side > max(180, min(crop.shape[:2]) * 0.90):
            continue

        red_density = red_pixels / float(max(1, width * height))
        compactness = min(width, height) / float(marker_side)
        relative_area = red_pixels / float(max(1, crop.shape[0] * crop.shape[1]))
        scale_score = min(1.0, relative_area * 80.0)
        score = min(1.0, red_density * 0.50 + compactness * 0.30 + scale_score * 0.20)
        components.append(
            {
                "score": round(float(score), 4),
                "red_pixels": red_pixels,
                "red_density": round(float(red_density), 4),
                "red_bbox_xyxy": [int(x), int(y), int(x + width), int(y + height)],
                "reason": "red_marker_candidate",
            }
        )

    if not components:
        return {"score": 0.0, "reason": "no_red_marker_candidate"}
    return max(components, key=lambda item: item["score"])


def clamp(value: float, minimum: float, maximum: float) -> float:
    return min(max(value, minimum), maximum)


def apply_nms(detections: list[Detection], iou_threshold: float, max_count: int) -> list[Detection]:
    if not detections:
        return []
    detections = sorted(detections, key=lambda det: det.confidence, reverse=True)
    kept: list[Detection] = []
    for detection in detections:
        if all(bbox_iou(detection.bbox_xyxy, kept_detection.bbox_xyxy) <= iou_threshold for kept_detection in kept):
            kept.append(detection)
        if len(kept) >= max_count:
            break
    return kept


def bbox_iou(box_a: tuple[float, float, float, float], box_b: tuple[float, float, float, float]) -> float:
    ax1, ay1, ax2, ay2 = box_a
    bx1, by1, bx2, by2 = box_b
    inter_x1 = max(ax1, bx1)
    inter_y1 = max(ay1, by1)
    inter_x2 = min(ax2, bx2)
    inter_y2 = min(ay2, by2)
    inter_area = max(0.0, inter_x2 - inter_x1) * max(0.0, inter_y2 - inter_y1)
    union_area = (
        max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
        + max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
        - inter_area
    )
    return inter_area / union_area if union_area else 0.0


def localize_frame_on_map(
    frame: np.ndarray,
    map_image: np.ndarray,
    args: argparse.Namespace,
) -> tuple[dict[str, Any], list[str]]:
    match_args = SimpleNamespace(
        method=args.map_method,
        orientations=args.orientations,
        max_features=args.max_features,
        ratio=args.ratio,
        min_matches=args.min_matches,
        min_inliers=args.min_inliers,
        min_template_score=args.min_template_score,
        template_scales=args.template_scales,
        orientation_switch_margin=args.orientation_switch_margin,
        feature_max_dim=args.feature_max_dim,
        match_workers=args.match_workers,
    )
    return find_best_match(map_image, frame, match_args)


def draw_detections_on_frame(image: np.ndarray, detections: list[Detection]) -> np.ndarray:
    output = image.copy()
    for index, detection in enumerate(detections, start=1):
        x1, y1, x2, y2 = [int(round(value)) for value in detection.bbox_xyxy]
        color = (0, 0, 255) if detection.detector.startswith("yolo:") else (0, 180, 255)
        callout_box = expand_box_for_display(
            detection.bbox_xyxy,
            image_width=image.shape[1],
            image_height=image.shape[0],
            min_width=160,
            min_height=160,
        )
        cx1, cy1, cx2, cy2 = [int(round(value)) for value in callout_box]
        cv2.rectangle(output, (cx1, cy1), (cx2, cy2), color, 6, cv2.LINE_AA)
        cv2.rectangle(output, (x1, y1), (x2, y2), (0, 255, 255), 3, cv2.LINE_AA)
        center_x, center_y = detection.center
        cv2.drawMarker(
            output,
            (int(round(center_x)), int(round(center_y))),
            (0, 0, 255),
            cv2.MARKER_CROSS,
            28,
            2,
            cv2.LINE_AA,
        )
        draw_label(
            output,
            f"veh_{index:03d} {detection.class_name} {detection.confidence:.2f}",
            (x1, max(24, y1 - 8)),
            (0, 0, 0),
            (255, 255, 255),
        )
    draw_detection_insets(output, detections)
    return output


def expand_box_for_display(
    bbox_xyxy: tuple[float, float, float, float],
    image_width: int,
    image_height: int,
    min_width: int,
    min_height: int,
) -> tuple[float, float, float, float]:
    x1, y1, x2, y2 = bbox_xyxy
    center_x = (x1 + x2) / 2.0
    center_y = (y1 + y2) / 2.0
    width = max(x2 - x1, float(min_width))
    height = max(y2 - y1, float(min_height))
    return (
        clamp(center_x - width / 2.0, 0, image_width - 1),
        clamp(center_y - height / 2.0, 0, image_height - 1),
        clamp(center_x + width / 2.0, 0, image_width - 1),
        clamp(center_y + height / 2.0, 0, image_height - 1),
    )


def draw_detection_insets(image: np.ndarray, detections: list[Detection], max_insets: int = 3) -> None:
    if not detections:
        return

    inset_width = min(720, max(360, image.shape[1] // 5))
    inset_height = min(430, max(240, image.shape[0] // 5))
    margin = 28
    gap = 18

    for index, detection in enumerate(detections[:max_insets], start=1):
        x1, y1, x2, y2 = detection.bbox_xyxy
        center_x, center_y = detection.center
        crop_half_side = max(120.0, (max(x2 - x1, y2 - y1) * 4.0))
        crop_x1 = int(clamp(center_x - crop_half_side, 0, image.shape[1] - 1))
        crop_y1 = int(clamp(center_y - crop_half_side, 0, image.shape[0] - 1))
        crop_x2 = int(clamp(center_x + crop_half_side, 0, image.shape[1]))
        crop_y2 = int(clamp(center_y + crop_half_side, 0, image.shape[0]))
        crop = image[crop_y1:crop_y2, crop_x1:crop_x2].copy()
        if crop.size == 0:
            continue

        resized = cv2.resize(crop, (inset_width, inset_height), interpolation=cv2.INTER_CUBIC)
        scale_x = inset_width / max(1, crop_x2 - crop_x1)
        scale_y = inset_height / max(1, crop_y2 - crop_y1)
        local_box = (
            int(round((x1 - crop_x1) * scale_x)),
            int(round((y1 - crop_y1) * scale_y)),
            int(round((x2 - crop_x1) * scale_x)),
            int(round((y2 - crop_y1) * scale_y)),
        )
        cv2.rectangle(resized, local_box[:2], local_box[2:], (0, 255, 255), 3, cv2.LINE_AA)
        cv2.drawMarker(
            resized,
            (int(round((center_x - crop_x1) * scale_x)), int(round((center_y - crop_y1) * scale_y))),
            (0, 0, 255),
            cv2.MARKER_CROSS,
            28,
            2,
            cv2.LINE_AA,
        )
        draw_label(
            resized,
            f"zoom veh_{index:03d} {detection.class_name} {detection.confidence:.2f}",
            (12, 28),
            (0, 0, 0),
            (255, 255, 255),
        )

        inset_x2 = image.shape[1] - margin
        inset_x1 = inset_x2 - inset_width
        inset_y1 = margin + (index - 1) * (inset_height + gap)
        inset_y2 = inset_y1 + inset_height
        if inset_y2 > image.shape[0] - margin:
            break
        image[inset_y1:inset_y2, inset_x1:inset_x2] = resized
        cv2.rectangle(image, (inset_x1, inset_y1), (inset_x2, inset_y2), (255, 255, 255), 5)
        cv2.rectangle(image, (inset_x1, inset_y1), (inset_x2, inset_y2), (0, 0, 255), 2, cv2.LINE_AA)
        cv2.line(
            image,
            (int(round(center_x)), int(round(center_y))),
            (inset_x1, inset_y1 + inset_height // 2),
            (0, 0, 255),
            3,
            cv2.LINE_AA,
        )


def draw_map_overlay(
    map_image: np.ndarray,
    match_result: dict[str, Any],
    localized_detections: list[dict[str, Any]],
) -> np.ndarray:
    output = map_image.copy()
    highlight_color = (0, 255, 255)
    vehicle_color = (0, 0, 255)
    corners = np.array(match_result["corners"], dtype=np.int32).reshape(-1, 1, 2)
    match_line_thickness = max(3, round(min(map_image.shape[:2]) / 320))
    cv2.polylines(output, [corners], True, highlight_color, match_line_thickness, cv2.LINE_AA)

    for item in localized_detections:
        if item.get("map_pixel") is None:
            continue
        pixel = item["map_pixel"]
        x = int(round(pixel["x"]))
        y = int(round(pixel["y"]))
        marker_size = max(34, round(min(map_image.shape[:2]) / 36))
        marker_thickness = max(3, round(min(map_image.shape[:2]) / 420))
        cv2.drawMarker(
            output,
            (x, y),
            vehicle_color,
            cv2.MARKER_TILTED_CROSS,
            marker_size,
            marker_thickness,
            cv2.LINE_AA,
        )
        gps = item["gps"]
        draw_label(
            output,
            f"{item['vehicle_id']} {gps['latitude']:.7f},{gps['longitude']:.7f}",
            (x + 10, y - 10),
            (0, 0, 0),
            (255, 255, 255),
        )

    center_x, center_y = match_result["center"]
    draw_label(
        output,
        f"frame match: {match_result['method']} score={float(match_result['score']):.4f}",
        (int(round(center_x)) + 12, int(round(center_y)) - 12),
        (0, 0, 0),
        (255, 255, 255),
    )
    draw_map_focus_inset(output, match_result, localized_detections)
    return output


def draw_map_focus_inset(
    output: np.ndarray,
    match_result: dict[str, Any],
    localized_detections: list[dict[str, Any]],
) -> None:
    highlight_color = (0, 255, 255)
    vehicle_color = (0, 0, 255)
    match_points = [tuple(point) for point in match_result["corners"]]
    if not match_points:
        return

    crop_box = focus_crop_box(match_points, output.shape[1], output.shape[0])
    x1, y1, x2, y2 = crop_box
    crop = output[y1:y2, x1:x2].copy()
    if crop.size == 0:
        return

    max_inset_width = min(max(760, output.shape[1] // 2), max(1, output.shape[1] - 48))
    max_inset_height = min(max(460, output.shape[0] // 3), max(1, output.shape[0] - 48))
    inset_scale = min(max_inset_width / crop.shape[1], max_inset_height / crop.shape[0])
    inset_width = max(1, int(round(crop.shape[1] * inset_scale)))
    inset_height = max(1, int(round(crop.shape[0] * inset_scale)))
    resized = cv2.resize(crop, (inset_width, inset_height), interpolation=cv2.INTER_CUBIC)
    scale_x = inset_width / max(1, x2 - x1)
    scale_y = inset_height / max(1, y2 - y1)

    inset_corners = transform_points_for_inset(match_result["corners"], x1, y1, scale_x, scale_y)
    cv2.polylines(
        resized,
        [np.array(inset_corners, dtype=np.int32).reshape(-1, 1, 2)],
        True,
        highlight_color,
        max(8, round(min(inset_width, inset_height) / 52)),
        cv2.LINE_AA,
    )
    for item in localized_detections:
        if item.get("map_pixel") is None:
            continue
        pixel = item["map_pixel"]
        local_x = int(round((float(pixel["x"]) - x1) * scale_x))
        local_y = int(round((float(pixel["y"]) - y1) * scale_y))
        cv2.drawMarker(
            resized,
            (local_x, local_y),
            vehicle_color,
            cv2.MARKER_TILTED_CROSS,
            max(44, round(min(inset_width, inset_height) / 10)),
            max(6, round(min(inset_width, inset_height) / 90)),
            cv2.LINE_AA,
        )
        gps = item.get("gps")
        if gps:
            draw_label(
                resized,
                f"{item['vehicle_id']} {gps['latitude']:.7f},{gps['longitude']:.7f}",
                (local_x + 12, local_y - 12),
                (0, 0, 0),
                (255, 255, 255),
            )

    draw_label(resized, "match zoom", (12, 28), (0, 0, 0), (255, 255, 255))
    target_x, target_y = inset_position(output.shape[1], output.shape[0], match_points, inset_width, inset_height)
    output[target_y : target_y + inset_height, target_x : target_x + inset_width] = resized
    cv2.rectangle(
        output,
        (target_x, target_y),
        (target_x + inset_width, target_y + inset_height),
        highlight_color,
        max(10, round(min(output.shape[:2]) / 180)),
        cv2.LINE_AA,
    )

    center_x, center_y = match_result["center"]
    inset_anchor = (target_x + inset_width // 2, target_y + inset_height // 2)
    cv2.line(
        output,
        (int(round(center_x)), int(round(center_y))),
        inset_anchor,
        highlight_color,
        max(6, round(min(output.shape[:2]) / 260)),
        cv2.LINE_AA,
    )


def focus_crop_box(
    points: list[tuple[float, float]],
    image_width: int,
    image_height: int,
) -> tuple[int, int, int, int]:
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    width = max(xs) - min(xs)
    height = max(ys) - min(ys)
    pad = max(18.0, width * 0.18, height * 0.18)
    x1 = int(clamp(min(xs) - pad, 0, image_width - 1))
    y1 = int(clamp(min(ys) - pad, 0, image_height - 1))
    x2 = int(clamp(max(xs) + pad, x1 + 1, image_width))
    y2 = int(clamp(max(ys) + pad, y1 + 1, image_height))
    return x1, y1, x2, y2


def transform_points_for_inset(
    points: list[tuple[float, float]],
    crop_x: int,
    crop_y: int,
    scale_x: float,
    scale_y: float,
) -> list[tuple[int, int]]:
    return [
        (
            int(round((float(x) - crop_x) * scale_x)),
            int(round((float(y) - crop_y) * scale_y)),
        )
        for x, y in points
    ]


def inset_position(
    image_width: int,
    image_height: int,
    focus_points: list[tuple[float, float]],
    inset_width: int,
    inset_height: int,
) -> tuple[int, int]:
    margin = max(24, round(min(image_width, image_height) / 70))
    focus_center_x = sum(point[0] for point in focus_points) / len(focus_points)
    focus_center_y = sum(point[1] for point in focus_points) / len(focus_points)
    place_right = focus_center_x < image_width / 2.0
    place_bottom = focus_center_y < image_height / 2.0
    x = image_width - inset_width - margin if place_right else margin
    y = image_height - inset_height - margin if place_bottom else margin
    return int(x), int(y)


def make_process_board(
    frame_overlay: np.ndarray,
    map_overlay: np.ndarray,
    localized_detections: list[dict[str, Any]],
    match_result: dict[str, Any],
) -> np.ndarray:
    left = resize_to_fit(frame_overlay, max_width=1400, max_height=820)
    right = resize_to_fit(map_overlay, max_width=1400, max_height=820)
    image_row_height = max(left.shape[0], right.shape[0])
    gutter = 24
    title_height = 72
    width = left.shape[1] + right.shape[1] + gutter
    panel_height = coordinate_panel_height(localized_detections)
    board = np.full((image_row_height + title_height + panel_height, width, 3), 245, dtype=np.uint8)
    draw_process_title(board, "1 UAV frame detections", (18, 44))
    draw_process_title(board, "2 projected map coordinates", (left.shape[1] + gutter + 18, 44))
    board[title_height : title_height + left.shape[0], 0 : left.shape[1]] = left
    x_offset = left.shape[1] + gutter
    board[title_height : title_height + right.shape[0], x_offset : x_offset + right.shape[1]] = right
    cv2.line(board, (left.shape[1] + gutter // 2, title_height), (left.shape[1] + gutter // 2, title_height + image_row_height), (210, 210, 210), 2)
    draw_coordinate_panel(
        board,
        top=title_height + image_row_height,
        width=width,
        localized_detections=localized_detections,
        match_result=match_result,
    )
    return board


def draw_process_title(board: np.ndarray, text: str, origin: tuple[int, int]) -> None:
    cv2.putText(
        board,
        text,
        origin,
        cv2.FONT_HERSHEY_SIMPLEX,
        0.95,
        (0, 0, 0),
        2,
        cv2.LINE_AA,
    )


def coordinate_panel_height(localized_detections: list[dict[str, Any]]) -> int:
    visible_rows = max(1, min(len(localized_detections), 6))
    overflow_note_height = 44 if len(localized_detections) > visible_rows else 0
    return 96 + visible_rows * 44 + overflow_note_height


def draw_coordinate_panel(
    board: np.ndarray,
    top: int,
    width: int,
    localized_detections: list[dict[str, Any]],
    match_result: dict[str, Any],
) -> None:
    panel = board[top:, :]
    panel[:] = (255, 255, 255)
    cv2.line(board, (0, top), (width, top), (180, 180, 180), 1, cv2.LINE_AA)

    font = cv2.FONT_HERSHEY_SIMPLEX
    margin = 16
    table_left = margin
    table_right = width - margin
    columns = [
        ("id", table_left),
        ("class / conf", table_left + 150),
        ("image center", table_left + 390),
        ("WGS84 lat, lon", table_left + 660),
        ("TWD97 x, y", table_left + 1050),
    ]

    cv2.putText(
        board,
        f"Vehicle coordinates  |  map match: {match_result['method']} score={float(match_result['score']):.4f}",
        (margin, top + 26),
        font,
        0.78,
        (0, 0, 0),
        2,
        cv2.LINE_AA,
    )
    header_top = top + 50
    header_bottom = top + 86
    cv2.rectangle(board, (table_left, header_top), (table_right, header_bottom), (238, 242, 246), -1)
    cv2.rectangle(board, (table_left, header_top), (table_right, header_bottom), (190, 190, 190), 1)

    for label, x in columns:
        cv2.putText(board, label, (x, top + 74), font, 0.62, (65, 65, 65), 2, cv2.LINE_AA)
    for _label, x in columns[1:]:
        cv2.line(board, (x - 12, header_top), (x - 12, board.shape[0] - 12), (220, 220, 220), 1, cv2.LINE_AA)

    if not localized_detections:
        cv2.putText(
            board,
            "No vehicle detections.",
            (margin, top + 126),
            font,
            0.72,
            (0, 0, 180),
            2,
            cv2.LINE_AA,
        )
        return

    visible_items = localized_detections[:6]
    for row_index, item in enumerate(visible_items):
        row_top = header_bottom + row_index * 44
        row_bottom = row_top + 44
        row_y = row_top + 30
        bg_color = (255, 255, 255) if row_index % 2 == 0 else (248, 250, 252)
        cv2.rectangle(board, (table_left, row_top), (table_right, row_bottom), bg_color, -1)
        cv2.line(board, (table_left, row_bottom), (table_right, row_bottom), (226, 226, 226), 1, cv2.LINE_AA)

        center = item["center_image_pixel"]
        gps = item.get("gps")
        twd97 = item.get("twd97")
        if gps and twd97:
            gps_text = f"{gps['latitude']:.8f}, {gps['longitude']:.8f}"
            twd97_text = f"{twd97['x']:.3f}, {twd97['y']:.3f}"
        else:
            gps_text = "localization failed"
            twd97_text = "-"
        values = [
            item["vehicle_id"],
            f"{item['class_name'][:14]} / {item['confidence']:.2f}",
            f"({center['x']:.1f}, {center['y']:.1f})",
            gps_text,
            twd97_text,
        ]
        for (_label, x), value in zip(columns, values):
            cv2.putText(board, value, (x, row_y), font, 0.66, (0, 0, 0), 2, cv2.LINE_AA)

    remaining = len(localized_detections) - len(visible_items)
    if remaining > 0:
        cv2.putText(
            board,
            f"... {remaining} more detections are in vehicle_localization.json / .csv",
            (margin, header_bottom + len(visible_items) * 44 + 32),
            font,
            0.66,
            (70, 70, 70),
            2,
            cv2.LINE_AA,
        )


def save_detection_crops(
    image: np.ndarray,
    detections: list[Detection],
    output_dir: Path,
) -> list[str]:
    crop_dir = output_dir / "crops"
    crop_dir.mkdir(parents=True, exist_ok=True)
    for stale_crop in crop_dir.glob("veh_*.jpg"):
        stale_crop.unlink()
    crop_paths: list[str] = []
    for index, detection in enumerate(detections, start=1):
        x1, y1, x2, y2 = [int(round(value)) for value in detection.bbox_xyxy]
        pad = 24
        x1 = max(0, x1 - pad)
        y1 = max(0, y1 - pad)
        x2 = min(image.shape[1], x2 + pad)
        y2 = min(image.shape[0], y2 + pad)
        crop = image[y1:y2, x1:x2]
        crop_path = crop_dir / f"veh_{index:03d}.jpg"
        write_image(crop_path, crop)
        crop_paths.append(str(crop_path))
    return crop_paths


def wgs84_to_twd97(latitude: float, longitude: float) -> tuple[float, float]:
    """Convert WGS84 lat/lon to TWD97 TM2 zone 121 easting/northing."""
    axis_a = 6378137.0
    axis_b = 6356752.314245
    lon0 = math.radians(121.0)
    k0 = 0.9999
    dx = 250000.0

    lat = math.radians(latitude)
    lon = math.radians(longitude)
    eccentricity_sq = 1.0 - (axis_b * axis_b) / (axis_a * axis_a)
    second_eccentricity_sq = eccentricity_sq / (1.0 - eccentricity_sq)
    sin_lat = math.sin(lat)
    cos_lat = math.cos(lat)
    tan_lat = math.tan(lat)

    n_radius = axis_a / math.sqrt(1.0 - eccentricity_sq * sin_lat * sin_lat)
    t = tan_lat * tan_lat
    c = second_eccentricity_sq * cos_lat * cos_lat
    a = cos_lat * (lon - lon0)
    meridian_arc = axis_a * (
        (1 - eccentricity_sq / 4 - 3 * eccentricity_sq**2 / 64 - 5 * eccentricity_sq**3 / 256)
        * lat
        - (3 * eccentricity_sq / 8 + 3 * eccentricity_sq**2 / 32 + 45 * eccentricity_sq**3 / 1024)
        * math.sin(2 * lat)
        + (15 * eccentricity_sq**2 / 256 + 45 * eccentricity_sq**3 / 1024) * math.sin(4 * lat)
        - (35 * eccentricity_sq**3 / 3072) * math.sin(6 * lat)
    )

    x = dx + k0 * n_radius * (
        a
        + (1 - t + c) * a**3 / 6
        + (5 - 18 * t + t**2 + 72 * c - 58 * second_eccentricity_sq) * a**5 / 120
    )
    y = k0 * (
        meridian_arc
        + n_radius
        * tan_lat
        * (
            a**2 / 2
            + (5 - t + 9 * c + 4 * c**2) * a**4 / 24
            + (61 - 58 * t + t**2 + 600 * c - 330 * second_eccentricity_sq) * a**6 / 720
        )
    )
    return x, y


def build_report(
    frame_path: Path,
    args: argparse.Namespace,
    detections: list[Detection],
    localized_items: list[dict[str, Any]],
    match_result: dict[str, Any],
    match_warnings: list[str],
    detector_warning: str | None,
    target_verifier_summary: dict[str, Any],
    outputs: dict[str, str],
    timings: dict[str, float],
) -> dict[str, Any]:
    warnings = list(match_warnings)
    if detector_warning:
        warnings.append(detector_warning)
    if float(match_result["score"]) < args.min_template_score and match_result["method"] == "template":
        warnings.append(
            "Map template score is below threshold; treat map coordinates as rough demo output."
        )
    if target_verifier_summary.get("enabled") and target_verifier_summary.get("kept_count") == 0:
        warnings.append("Target verifier rejected all vehicle candidates; using map-match center fallback.")
    for item in localized_items:
        if item.get("localization_warning"):
            warnings.append(f"{item['vehicle_id']}: {item['localization_warning']}")

    report = {
        "frame": str(frame_path),
        "map_image": str(args.map_image),
        "detector": args.detector,
        "yolo_model": args.yolo_model,
        "detections_count": len(detections),
        "target_verifier": target_verifier_summary,
        "map_match": {
            "method": match_result["method"],
            "score": match_result["score"],
            "orientation": match_result["orientation"],
            "center_pixel": {
                "x": round(float(match_result["center"][0]), 3),
                "y": round(float(match_result["center"][1]), 3),
            },
            "corners_pixel": [
                {"x": round(float(x), 3), "y": round(float(y), 3)}
                for x, y in match_result["corners"]
            ],
            "orientation_scores": match_result.get("orientation_scores", []),
        },
        "vehicles": localized_items,
        "outputs": outputs,
        "timings_seconds": timings,
        "warnings": warnings,
        "deferred_work": [
            "Train or fine-tune a competition-specific detector for the roof marker X.",
            "Use drone GPS/IMU or manually selected stable-landmark ROI to constrain map matching.",
            "Add multi-frame tracking so the same vehicle is assigned a stable ID over time.",
        ],
    }
    if "feature_scale" in match_result:
        report["map_match"]["feature_scale"] = match_result["feature_scale"]
    return report


def localize_detections(
    detections: list[Detection],
    match_result: dict[str, Any],
    georef: Any,
    frame_shape: tuple[int, ...],
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    frame_height, frame_width = frame_shape[:2]
    query_roi = (0, 0, frame_width, frame_height)
    if not detections:
        return [fallback_map_center_item(match_result, georef, frame_width, frame_height)]

    for index, detection in enumerate(detections, start=1):
        center_x, center_y = detection.center
        item: dict[str, Any] = {
            "vehicle_id": f"veh_{index:03d}",
            "class_name": detection.class_name,
            "confidence": round(detection.confidence, 4),
            "detector": detection.detector,
            "bbox_xyxy": [round(float(value), 3) for value in detection.bbox_xyxy],
            "center_image_pixel": {"x": round(center_x, 3), "y": round(center_y, 3)},
        }
        if detection.target_verification is not None:
            item["target_verification"] = detection.target_verification
        try:
            map_x, map_y = map_query_point(match_result, (center_x, center_y), query_roi)
            apply_map_coordinates(item, map_x, map_y, georef, "mapped point")
        except Exception as exc:
            item["map_pixel"] = None
            item["gps"] = None
            item["twd97"] = None
            item["localization_error"] = str(exc)
        items.append(item)
    return items


def fallback_map_center_item(
    match_result: dict[str, Any],
    georef: Any,
    frame_width: int,
    frame_height: int,
) -> dict[str, Any]:
    center_x, center_y = match_result["center"]
    item: dict[str, Any] = {
        "vehicle_id": "fallback_map_center",
        "class_name": "map_match_center_fallback",
        "confidence": 0.0,
        "detector": "fallback:map_match_center",
        "bbox_xyxy": [],
        "center_image_pixel": {"x": round(frame_width / 2.0, 3), "y": round(frame_height / 2.0, 3)},
        "is_fallback": True,
        "fallback_reason": "no_verified_vehicle_detections",
    }
    try:
        apply_map_coordinates(item, float(center_x), float(center_y), georef, "map center")
    except Exception as exc:
        item["map_pixel"] = None
        item["gps"] = None
        item["twd97"] = None
        item["localization_error"] = str(exc)
    return item


def apply_map_coordinates(item: dict[str, Any], map_x: float, map_y: float, georef: Any, label: str) -> None:
    clamped_x = clamp(float(map_x), 0.0, float(georef.width))
    clamped_y = clamp(float(map_y), 0.0, float(georef.height))
    was_clamped = not math.isclose(clamped_x, map_x, abs_tol=1e-6) or not math.isclose(clamped_y, map_y, abs_tol=1e-6)

    latitude, longitude = georef.pixel_to_gps(clamped_x, clamped_y)
    twd97_x, twd97_y = wgs84_to_twd97(latitude, longitude)
    item["map_pixel"] = {"x": round(clamped_x, 3), "y": round(clamped_y, 3)}
    item["gps"] = {"latitude": round(latitude, 8), "longitude": round(longitude, 8)}
    item["twd97"] = {"x": round(twd97_x, 3), "y": round(twd97_y, 3)}
    if was_clamped:
        item["map_pixel_clamped"] = True
        item["original_map_pixel"] = {"x": round(float(map_x), 3), "y": round(float(map_y), 3)}
        item["localization_warning"] = (
            f"{label} ({map_x:.2f}, {map_y:.2f}) outside reference map; "
            f"using nearest boundary point ({clamped_x:.2f}, {clamped_y:.2f})"
        )


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_csv(path: Path, items: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=[
                "vehicle_id",
                "class_name",
                "confidence",
                "bbox_xyxy",
                "center_image_x",
                "center_image_y",
                "map_x",
                "map_y",
                "latitude",
                "longitude",
                "twd97_x",
                "twd97_y",
            ],
        )
        writer.writeheader()
        for item in items:
            map_pixel = item.get("map_pixel") or {}
            gps = item.get("gps") or {}
            twd97 = item.get("twd97") or {}
            center = item["center_image_pixel"]
            writer.writerow(
                {
                    "vehicle_id": item["vehicle_id"],
                    "class_name": item["class_name"],
                    "confidence": item["confidence"],
                    "bbox_xyxy": json.dumps(item["bbox_xyxy"]),
                    "center_image_x": center["x"],
                    "center_image_y": center["y"],
                    "map_x": map_pixel.get("x"),
                    "map_y": map_pixel.get("y"),
                    "latitude": gps.get("latitude"),
                    "longitude": gps.get("longitude"),
                    "twd97_x": twd97.get("x"),
                    "twd97_y": twd97.get("y"),
                }
            )


def timing_seconds(start_time: float) -> float:
    return round(time.perf_counter() - start_time, 4)


def print_timing_summary(timings: dict[str, float]) -> None:
    parts = [f"{name}={seconds:.3f}s" for name, seconds in timings.items()]
    print("Timing: " + ", ".join(parts), file=sys.stderr)


def main() -> int:
    total_start = time.perf_counter()
    timings: dict[str, float] = {}

    args = parse_args()
    if args.output_dir is None:
        args.output_dir = DEFAULT_OUTPUT_ROOT / args.frame.stem
    upscales = parse_float_list(args.tile_upscales, "--tile-upscales")
    class_filter = parse_class_filter(args.vehicle_classes)

    stage_start = time.perf_counter()
    frame = read_bgr(args.frame)
    args.map_image = resolve_map_image_path(args)
    map_image = read_bgr(args.map_image)
    georef = load_georef(args.georef_json)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    timings["load_inputs"] = timing_seconds(stage_start)

    stage_start = time.perf_counter()
    detector_warning = None
    if args.detector in {"auto", "yolo"}:
        try:
            detections = detect_with_yolo(frame, args, upscales, class_filter)
        except RuntimeError as exc:
            if args.detector == "yolo":
                raise
            detector_warning = str(exc)
            detections = detect_white_vehicle_candidates(frame, args)
    else:
        detections = detect_white_vehicle_candidates(frame, args)
    if args.target_verifier and args.target_verifier_proposals:
        target_marker_candidates = detect_target_marker_vehicle_candidates(frame, args)
        detections = apply_nms(
            detections + target_marker_candidates,
            args.nms_iou,
            args.max_detections,
        )
    timings["detect_vehicles"] = timing_seconds(stage_start)

    stage_start = time.perf_counter()
    detections, target_verifier_summary = filter_target_detections(frame, detections, args)
    timings["verify_targets"] = timing_seconds(stage_start)

    stage_start = time.perf_counter()
    match_result, match_warnings = localize_frame_on_map(frame, map_image, args)
    timings["match_map"] = timing_seconds(stage_start)

    stage_start = time.perf_counter()
    localized_items = localize_detections(detections, match_result, georef, frame.shape)
    timings["project_coordinates"] = timing_seconds(stage_start)

    stage_start = time.perf_counter()
    frame_overlay = draw_detections_on_frame(frame, detections)
    map_overlay = draw_map_overlay(map_image, match_result, localized_items)
    process_board = make_process_board(frame_overlay, map_overlay, localized_items, match_result)
    timings["render_visualizations"] = timing_seconds(stage_start)

    frame_overlay_path = args.output_dir / "01_frame_vehicle_detections.jpg"
    map_overlay_path = args.output_dir / "02_map_vehicle_coordinates.jpg"
    board_path = args.output_dir / "03_process_overview.jpg"
    json_path = args.output_dir / "vehicle_localization.json"
    csv_path = args.output_dir / "vehicle_localization.csv"

    stage_start = time.perf_counter()
    write_image(frame_overlay_path, frame_overlay)
    write_image(map_overlay_path, map_overlay)
    write_image(board_path, process_board)

    crop_paths = save_detection_crops(frame, detections, args.output_dir) if args.save_crops else []
    for item, crop_path in zip(localized_items, crop_paths):
        item["crop"] = crop_path
    write_csv(csv_path, localized_items)
    timings["write_outputs"] = timing_seconds(stage_start)

    outputs = {
        "frame_overlay": str(frame_overlay_path),
        "map_overlay": str(map_overlay_path),
        "process_overview": str(board_path),
        "json": str(json_path),
        "csv": str(csv_path),
    }
    timings["total"] = timing_seconds(total_start)
    report = build_report(
        args.frame,
        args,
        detections,
        localized_items,
        match_result,
        match_warnings,
        detector_warning,
        target_verifier_summary,
        outputs,
        timings,
    )
    write_json(json_path, report)

    print_timing_summary(timings)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if args.show:
        show_image("vehicle localization process overview", process_board)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1)
